"""Add messages table

Revision ID: 9270f4abcee5
Revises: ab8296a74e19
Create Date: 2022-12-11 18:34:22.003716

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9270f4abcee5'
down_revision = 'ab8296a74e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_on', sa.DateTime(), nullable=False),
                    sa.Column('updated_on', sa.DateTime(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('recording_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['recording_id'], ['files.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
